CREATE TABLE ENFERMOS(
code VARCHAR(8) NOT NULL,
nome VARCHAR(8) NOT NULL,
dire VARCHAR(8) NOT NULL)

CREATE TABLE CONSUMO(
code VARCHAR(8) NOT NULL,
codf VARCHAR(8) NOT NULL,
unidades int NOT NULL)

CREATE TABLE FARMACOS (
codf VARCHAR(8) NOT NULL,
nomf VARCHAR(8) NOT NULL,
tipof VARCHAR(8) NOT NULL,
preciounidad DECIMAL(10,2) NOT NULL)

CREATE TABLE TIPOSFARMACO(
tipof VARCHAR(8) NOT NULL,
descripcion VARCHAR(20) NOT NULL,
caracteristicas VARCHAR(20) NOT NULL)

ALTER TABLE ENFERMOS 
ADD CONSTRAINT pk_enfermos PRIMARY KEY (code);

ALTER TABLE CONSUMO 
ADD CONSTRAINT pk_consumo PRIMARY KEY (code,codf);

ALTER TABLE FARMACOS 
ADD CONSTRAINT pk_farmacos PRIMARY KEY (codf);

ALTER TABLE TIPOSFARMACO 
ADD CONSTRAINT pk_tiposfarmaco PRIMARY KEY (tipof);

ALTER TABLE FARMACOS
ADD CONSTRAINT fk_tipof 
FOREIGN KEY (tipof) REFERENCES TIPOSFARMACO(tipof) 
ON DELETE SET NULL;

ALTER TABLE CONSUMO
ADD CONSTRAINT fk_code 
FOREIGN KEY (code) REFERENCES ENFERMOS(code);