--BORRAMOS LAS TABLAS YA EXISTENTES
DROP TABLE LIBRO;
DROP TABLE USUARIO;
DROP TABLE CLASE;
DROP TABLE PRESTAMO;

--CREAMOS LAS TABLAS
CREATE TABLE LIBRO(
codigo VARCHAR(8),--PK
autor VARCHAR(20),
titulo VARCHAR(20),
editor VARCHAR(20),
clase VARCHAR(20),--FK
prestado VARCHAR(1));

CREATE TABLE USUARIO(
secuencia VARCHAR(8),
nombre VARCHAR(20),
direccion VARCHAR(20),
fecha_ingreso DATE);

CREATE TABLE CLASE (
clave VARCHAR(20),--PK
tiempo_de_prestamo NUMBER);

CREATE TABLE PRESTAMO (
codigo VARCHAR(20),--FK1 PK
secuencia VARCHAR(8),--FK2 PK
fecha_inicio DATE);

--AGREGAMOS PK
ALTER TABLE LIBRO 
ADD CONSTRAINT pk_libro PRIMARY KEY (codigo);

ALTER TABLE USUARIO
ADD CONSTRAINT pk_usuario PRIMARY KEY (secuencia);

ALTER TABLE CLASE
ADD CONSTRAINT pk_clase PRIMARY KEY (clave);

ALTER TABLE PRESTAMO
ADD CONSTRAINT pk_prestamo PRIMARY KEY (codigo,secuencia);
--AGREGAMOS FK
ALTER TABLE LIBRO
ADD CONSTRAINT fk_libro_clase FOREIGN KEY (clase) REFERENCES CLASE (clave);

ALTER TABLE PRESTAMO
ADD CONSTRAINT fk_prestamo_libro FOREIGN KEY (codigo) REFERENCES LIBRO(codigo);
ALTER TABLE PRESTAMO
ADD CONSTRAINT fk_prestamo_usuario  FOREIGN KEY (secuencia) REFERENCES USUARIO(secuencia);

ALTER TABLE LIBRO
MODIFY prestado VARCHAR(1) DEFAULT (1);

ALTER TABLE USUARIO
MODIFY fecha_ingreso NOT NULL;